// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 撮影日 (cam_files.date) 別の集計 (Refs #12)
 */
export type DayStat = { date: string, 
/**
 * cam_files の行数
 */
files: bigint, 
/**
 * flickr_id 付与済み (= Flickr アップロード済み)
 */
uploaded: bigint, 
/**
 * flickr_photo 登録済み (= /import で検証済み)
 */
verified: bigint, };
