// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 検証済み Flickr 写真 (flickr_photo へ登録した行)
 */
export type FlickrPhoto = { id: string, secret: string, server: string, };
