// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST /import のリクエスト (body は省略可)
 */
export type ImportRequest = { 
/**
 * 1 回で処理する最大件数 (default 500)
 */
limit?: number, };
