// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlickrPhoto } from "./FlickrPhoto";

/**
 * POST /import のレスポンス
 */
export type ImportResponse = { imported_count: number, errors_count: number, remaining_count: number, photos: Array<FlickrPhoto>, };
