// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST /oauth/callback のレスポンス。
 * access token / secret は DB に保存するのみで **echo しない**
 * (旧 gRPC `TokenResponse` はトークンを返していたが、front は使っておらず
 * レスポンス経由の値漏れを避けるため意図的に落とした)。
 */
export type OauthCallbackResponse = { user_nsid: string, username: string, saved: boolean, };
