// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GET /oauth/url のレスポンス
 */
export type OauthUrlResponse = { authorization_url: string, request_token: string, request_token_secret: string, };
