// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST /oauth/callback のリクエスト
 */
export type OauthCallbackRequest = { oauth_token: string, oauth_verifier: string, request_token_secret: string, };
