// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayStat } from "./DayStat";

/**
 * GET /stats のレスポンス (Refs #12)
 */
export type StatsResponse = { 
/**
 * 直近 N 日 (新しい順)
 */
days: Array<DayStat>, 
/**
 * 全期間の flickr_id IS NULL 残数
 */
total_unuploaded: bigint, 
/**
 * 全期間の flickr_photo 未登録残数
 */
total_unverified: bigint, 
/**
 * 最古の未アップロード撮影日 (YYYYMMDD)。upload は古い順なので、
 * この値が日々進む = backfill が SD ローテーションに勝っている目印
 */
oldest_unuploaded_date?: string, };
