// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST /sync のリクエスト (body は省略可、Refs #9)
 */
export type SyncRequest = { 
/**
 * 1 回で Flickr にアップロードする最大件数 (default 50)。
 * 0 で upload を skip し cam_files の同期のみ行う。
 * cf-flickr-proxy (edge 100s) 経由で呼ぶ場合は小さい値を渡すこと
 */
upload_limit?: number, };
