// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST /sync のレスポンス (Refs #9)。
 * 旧 SyncCamFilesResponse との差: upload を同期実行に変えたので
 * `flickr_upload_started` (= 件数を投げただけ) ではなく実績
 * (`uploaded_count` / `upload_errors`) を返す
 */
export type SyncResponse = { 
/**
 * カメラ上で走査対象になった日付ディレクトリ数
 */
processed_dates: number, 
/**
 * 走査対象になった (日付, 時間) ディレクトリ数
 */
processed_hours: number, 
/**
 * cam_files に UPSERT した件数
 */
new_files: number, 
/**
 * flickr_tokens に access token があったか
 * (false の場合 upload は skip される — 認可は GET /oauth/url から)
 */
flickr_token_present: boolean, 
/**
 * Flickr へのアップロード成功数
 */
uploaded_count: number, 
/**
 * アップロード失敗数 (個別失敗は処理継続、詳細は log)
 */
upload_errors: number, 
/**
 * camera CGI が text/plain を返したため SD_ZOMBIE センチネルで
 * マークした件数 (= SD 上に実体が無くなった file の自動回収、Refs #26)
 */
zombied_count: number, 
/**
 * flickr_id IS NULL で残っている件数 (次回 sync で続きから処理)
 */
remaining_unuploaded: number, message: string, };
